name: App Build & Test

on:
  push:
    branches:
    - feature/*
    - hotfix/*
    - release/*
    paths:
    - 'src/**/**'
    - 'test/**/**'

jobs:
  functionapp_build_test_deploy_dev:
    name: 'FunctionApp Build & Test'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK for 3.1 LTS
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Setup .NET SDK for 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x'

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore .

    - name: Build solution
      shell: bash
      run: |
        dotnet build . -c Release

    - name: Test solution
      shell: bash
      run: |
        dotnet test . -c Release
