name: Resource Build, Test & Deploy

on:
  push:
    branches:
    - main
    paths:
    - 'resources/**'

jobs:
  arm_template_build_test_deploy_dev:
    name: 'ARM Templates Build, Test & Deploy'

    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP_NAME: 'rg-${{ secrets.RESOURCE_NAME }}-${{ secrets.LOCATION_CODE }}'

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # enable-AzPSSession: true

    - name: Deploy ARM templates for FlowHelper
      uses: Azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        deploymentName: 'flow_helper'
        template: 'resources/azuredeploy.bicep'
        parameters: name=${{ secrets.RESOURCE_NAME }} instanceName=${{ secrets.INSTANCE_FLOW_HELPER }} locationCode=${{ secrets.LOCATION_CODE }} faceApiSkuToProvision=false openApiDocTitle="${{ secrets.DOCTITLE_FLOW_HELPER }}"
        failOnStdErr: false

    - name: Deploy ARM templates for FaceRecogniser
      uses: Azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        deploymentName: 'face_recogniser'
        template: 'resources/azuredeploy.bicep'
        parameters: name=${{ secrets.RESOURCE_NAME }} instanceName=${{ secrets.INSTANCE_FACE_RECOGNISER }} locationCode=${{ secrets.LOCATION_CODE }} faceApiSkuToProvision=true faceApiSku=S0 openApiDocTitle="${{ secrets.DOCTITLE_FACE_RECOGNISER }}"
        failOnStdErr: false
